services:
  - type: web
    name: my-community-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://mycommunity-api.onrender.com
    healthCheckPath: /
    autoDeploy: true
