# Generated by Django 5.1.4 on 2025-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
