name: Frontend CI/CD

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build-and-test:
    name: Frontend Checks
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
        continue-on-error: false

      - name: Build project
        working-directory: frontend
        run: npm run build
        continue-on-error: false
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
