name: Frontend CI/CD

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build-and-test:
    name: Frontend Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
        continue-on-error: false

      - name: Build project
        working-directory: frontend
        run: npm run build
        continue-on-error: false

      - name: Install wait-on utility
        run: npm install -g wait-on

      - name: Start Next.js server
        working-directory: frontend
        run: npm run dev & wait-on http://localhost:3000 -t 60000
        env:
          # Add any environment variables needed for the dev server
          NODE_ENV: development

      - name: Run tests
        working-directory: frontend
        run: npm test
        env:
          CI: true
          CYPRESS_baseUrl: http://localhost:3000
        continue-on-error: false
